version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: qaservice
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #  MYSQL_ROOT_PASSWORD: root
    #volumes:
    #  - ./docker/db:/docker-entrypoint-initdb.d
    volumes:
      - ./mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"

        #adminer:
        #image: adminer
        #restart: always
        #ports:
        #- 8888:8080
        #
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  tomcat:
    image: tomcat:7.0
    container_name: tomcat
    #environment:
    #  TOMCAT_HTTP_PORT_NUMBER: 5004
    volumes:
      - ./dist/ROOT.war:/usr/local/tomcat/webapps/TrafficQAService.war
        #      - ./tomcat:/usr/local/tomcat
    ports:
      - "5004:8080"
    environment:
      MYSQL_HOST: db
    links:
      - mysql:db
    depends_on:
      - mysql
